id: I44BABEC8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:16:21+00:00'
last_modified: '2022-06-08T02:06:45.397478+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23685
  title: འདོན་ཆ་ཉེར་མཁོ་ཕན་བདེའི་བུམ་བཟང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E3E5:
      image_group_id: I2464
      title: ''
      total_pages: 594
      order: 1
      base_file: E3E5.txt
    28D3:
      image_group_id: I2465
      title: ''
      total_pages: 880
      order: 2
      base_file: 28D3.txt
    691C:
      image_group_id: I2466
      title: ''
      total_pages: 754
      order: 3
      base_file: 691C.txt
    EA35:
      image_group_id: I2467
      title: ''
      total_pages: 646
      order: 4
      base_file: EA35.txt
    ACA7:
      image_group_id: I2468
      title: ''
      total_pages: 800
      order: 5
      base_file: ACA7.txt
    940A:
      image_group_id: I2469
      title: ''
      total_pages: 536
      order: 6
      base_file: 940A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
