id: I44BABEC8
legacy_id: P004584
ocr_import_info:
  bdrc_scan_id: W23685
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T13:12:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:52:18.405291+00:00'
last_modified: 2022-09-02 09:55:47.667892
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23685
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23685
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདོན་ཆ་ཉེར་མཁོ་ཕན་བདེའི་བུམ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.7682050716505676
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I2468:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2468
      total_pages: 800
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2468.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7567130852156501
    legacy_id: v005
  I2464:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2464
      total_pages: 594
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2464.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7730576387799254
    legacy_id: v001
  I2469:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2469
      total_pages: 536
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2469.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7419534186883457
    legacy_id: v006
  I2466:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2466
      total_pages: 754
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2466.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7685103071913031
    legacy_id: v003
  I2467:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2467
      total_pages: 646
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2467.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.8007787107337917
    legacy_id: v004
  I2465:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2465
      total_pages: 880
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2465.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7654135509573449
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
